### ISSUE TITLE
Figure out what absolute paths should match

### ISSUE THREAD

**Issue by ndmitchell** [eborden/filepattern#1]
The Shake paths, as per https://github.com/ndmitchell/shake/issues/376, don't match absolute paths - so `**/*.c` will match `test/foo.c` but not `/test/foo.c` or `C:/test/foo.c`. While it's somewhat useful, it's highly inconsistent in the code, and requires deciding whether `C:foo.c` or `/foo.c` are relative or absolute on Windows (in truth they are bit of both...). My inclination is that when moving to a `filepattern` library that whole relative/absolute mess should be thrown out, and `**/foo.c` should be equivalent to `takeFileName x == "foo.c"`, regardless of absolute vs relative.

My thoughts are that if people want to avoid matching relative paths in their Shake build system they can do:

```haskell
priority 100 $ isAbsolute ?> \_ -> return ()
```

Namely add a rule with top priority that always matches absolute paths and doesn't build them.

I did a dummy removal of the absolute/relative stuff and a lot of tests got simpler, in particular those about `walker` and `?==` correspondence, which certainly suggests it is the right semantics.

CC @eborden @ezyang @snowleopard

**Comment by snowleopard** [comment]
I agree: `isAbsolute`/`isRelative` logic is non-obvious and including it into default matching `?==` makes the latter difficult to understand (and test).

One can always do `matchRelative p f = isRelative f && p ?== f` to recover the current behaviour.

**Comment by eborden** [comment]
:+1: from me on this.

**Comment by ndmitchell** [comment]
Cool, following that plan now, and will add some notes to Shake.

**Comment by ndmitchell** [comment]
Done, and I set up a changelog for filepattern to record all the changes relative to Shake.
