### ISSUE TITLE
Figure out what to do with '.'

### ISSUE THREAD

**Issue by ndmitchell** [eborden/filepattern#2]
Currently when matching a FilePattern and FilePath, if there is a `.` in the FilePattern, that can either match a literal `.` in the FilePath, or be ignored. Conversely, every `.` in a FilePath must be matched explicitly or with something like `*` or `**`. That behaviour is confusing and weird. I see two sensible possible routes forward:

1. Ignore all `.` paths in both FilePattern and FilePath.
2. Declare that `.` has no special behaviour in either - it can be matched literally, but nothing else.

The concern with option 2 is that when walking a directory structure, `.` really does have no meaning, so it is a bit inconsistent. The concern with option 1 is that it's magic behaviour that isn't otherwise well founded. Thoughts? (CC @eborden and @snowleopard)

**Comment by snowleopard** [comment]
> 1. Ignore all `.` paths in both FilePattern and FilePath.

@ndmitchell Well, I guess it's not just ignoring it. You wouldn't want `file` to match pattern `.file`. If I understand correctly, you suggest to treat `./` as being equal to `/` -- the latter sounds fine to me and easy to document/remember.

**Comment by snowleopard** [comment]
Oh, just realised there is also `../` which is not equal to `./`. So, the precise rule is not as easy to formulate as I thought :)

**Comment by ndmitchell** [comment]
I mean only `.` which are an entire directory - so `./foo/./bar/./baz` would be equivalent to `foo/bar/baz`, but `.foo` remains `.foo`. You have to do nothing on `..` because symlinks mean any semantics you might have hoped for don't hold.

**Comment by snowleopard** [comment]
Yes, this sounds right.

I think I prefer this option, because there is only one possible interpretation of `./foo/./bar/./baz`.

(I think the intuition here is the same as with defining instances: if there is only one possible instance definition, it should be defined, so that users don't have to do this.)

**Comment by ndmitchell** [comment]
To confirm, @snowleopard is in favour of essentially `joinPath . filter (/= ".") . splitDirectories` on both sides before doing any matching?

**Comment by snowleopard** [comment]
@ndmitchell Yes.

**Comment by eborden** [comment]
Sorry, catching up on this. So to be clear, we are speaking about "orphaned" `.` symbols: `./`, `/./` and `/.`; Not `.` symbols that are paired with another symbol: `..`, `.foo`, `bar.`, `foo.bar`?

**Comment by ndmitchell** [comment]
Yep, only orphaned `.` symbols

**Comment by eborden** [comment]
Then I am :+1: on ignoring them.

**Comment by ndmitchell** [comment]
Done as suggested - plenty of corner cases but I've used the test properties to guide me.
