### ISSUE TITLE
Release 0.1.0.0

### ISSUE THREAD

**Issue by eborden** [eborden/filepattern#3]
Let's release `filepattern` on hackage. What is left to do?

@ndmitchell In [this comment](https://github.com/ndmitchell/shake/pull/551#issuecomment-349785181) you mentioned wanting to make other changes. Could you enumerate them here so that they can be tackled?

**Comment by ndmitchell** [comment]
I've been pushing patches at https://github.com/ndmitchell/filepattern. There's a semantic issue around extract vs substitute I want to resolve, which requires a few hours at a whiteboard. Once that's done I'll be in a place to release it - it's at the top of my stack now.

**Comment by ndmitchell** [comment]
Finally, done! I resolved the semantic issue, added directory pieces etc. I intend to maintain it at https://github.com/ndmitchell/filepattern going forward, since that's where my other repos are, and I suspect I may need to adjust it as part of the move to Shake.
